/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_imslib_WRAP_H_
#define SWIG_imslib_WRAP_H_

#include <map>
#include <string>


class SwigDirector_IEventHandler : public iMS::IEventHandler, public Swig::Director {

public:
    SwigDirector_IEventHandler(PyObject *self);
    virtual ~SwigDirector_IEventHandler();
    virtual void EventAction(void *sender,int const message);
    virtual void EventAction(void *sender,int const message,int const param);
    virtual void EventAction(void *sender,int const message,int const param,int const param2);
    virtual void EventAction(void *sender,int const message,double const param);
    virtual void EventAction(void *sender,int const message,int const param,std::vector< uint8_t,std::allocator< uint8_t > > const data);

/* Internal director utilities */
public:
    bool swig_get_inner(const char *swig_protected_method_name) const {
      std::map<std::string, bool>::const_iterator iv = swig_inner.find(swig_protected_method_name);
      return (iv != swig_inner.end() ? iv->second : false);
    }
    void swig_set_inner(const char *swig_protected_method_name, bool swig_val) const {
      swig_inner[swig_protected_method_name] = swig_val;
    }
private:
    mutable std::map<std::string, bool> swig_inner;

#if defined(SWIG_PYTHON_DIRECTOR_VTABLE)
/* VTable implementation */
    PyObject *swig_get_method(size_t method_index, const char *method_name) const {
      PyObject *method = vtable[method_index];
      if (!method) {
        swig::SwigVar_PyObject name = SWIG_Python_str_FromChar(method_name);
        method = PyObject_GetAttr(swig_get_self(), name);
        if (!method) {
          std::string msg = "Method in class IEventHandler doesn't exist, undefined ";
          msg += method_name;
          Swig::DirectorMethodException::raise(msg.c_str());
        }
        vtable[method_index] = method;
      }
      return method;
    }
private:
    mutable swig::SwigVar_PyObject vtable[5];
#endif

};


class SwigDirector_CS_ETH : public iMS::CS_ETH, public Swig::Director {

public:
    SwigDirector_CS_ETH(PyObject *self,bool use_dhcp=false,std::string addr=std::string("192.168.1.10"),std::string netmask=std::string("255.255.255.0"),std::string gw=std::string("192.168.1.1"));
    virtual ~SwigDirector_CS_ETH();

/* Internal director utilities */
public:
    bool swig_get_inner(const char *swig_protected_method_name) const {
      std::map<std::string, bool>::const_iterator iv = swig_inner.find(swig_protected_method_name);
      return (iv != swig_inner.end() ? iv->second : false);
    }
    void swig_set_inner(const char *swig_protected_method_name, bool swig_val) const {
      swig_inner[swig_protected_method_name] = swig_val;
    }
private:
    mutable std::map<std::string, bool> swig_inner;
};


class SwigDirector_CS_RS422 : public iMS::CS_RS422, public Swig::Director {

public:
    SwigDirector_CS_RS422(PyObject *self);
    SwigDirector_CS_RS422(PyObject *self,unsigned int baud_rate);
    SwigDirector_CS_RS422(PyObject *self,std::vector< std::uint8_t,std::allocator< std::uint8_t > > process_data);
    virtual ~SwigDirector_CS_RS422();

/* Internal director utilities */
public:
    bool swig_get_inner(const char *swig_protected_method_name) const {
      std::map<std::string, bool>::const_iterator iv = swig_inner.find(swig_protected_method_name);
      return (iv != swig_inner.end() ? iv->second : false);
    }
    void swig_set_inner(const char *swig_protected_method_name, bool swig_val) const {
      swig_inner[swig_protected_method_name] = swig_val;
    }
private:
    mutable std::map<std::string, bool> swig_inner;
};


struct SwigDirector_SequenceEntry : public iMS::SequenceEntry, public Swig::Director {

public:
    SwigDirector_SequenceEntry(PyObject *self);
    SwigDirector_SequenceEntry(PyObject *self,std::array< std::uint8_t,16 > const &uuid,int const rpts=0);
    SwigDirector_SequenceEntry(PyObject *self,iMS::SequenceEntry const &arg0);
    virtual ~SwigDirector_SequenceEntry();
    virtual bool operator ==(iMS::SequenceEntry const &rhs) const;

/* Internal director utilities */
public:
    bool swig_get_inner(const char *swig_protected_method_name) const {
      std::map<std::string, bool>::const_iterator iv = swig_inner.find(swig_protected_method_name);
      return (iv != swig_inner.end() ? iv->second : false);
    }
    void swig_set_inner(const char *swig_protected_method_name, bool swig_val) const {
      swig_inner[swig_protected_method_name] = swig_val;
    }
private:
    mutable std::map<std::string, bool> swig_inner;

#if defined(SWIG_PYTHON_DIRECTOR_VTABLE)
/* VTable implementation */
    PyObject *swig_get_method(size_t method_index, const char *method_name) const {
      PyObject *method = vtable[method_index];
      if (!method) {
        swig::SwigVar_PyObject name = SWIG_Python_str_FromChar(method_name);
        method = PyObject_GetAttr(swig_get_self(), name);
        if (!method) {
          std::string msg = "Method in class SequenceEntry doesn't exist, undefined ";
          msg += method_name;
          Swig::DirectorMethodException::raise(msg.c_str());
        }
        vtable[method_index] = method;
      }
      return method;
    }
private:
    mutable swig::SwigVar_PyObject vtable[1];
#endif

};


struct SwigDirector_ImageSequenceEntry : public iMS::ImageSequenceEntry, public Swig::Director {

public:
    SwigDirector_ImageSequenceEntry(PyObject *self);
    SwigDirector_ImageSequenceEntry(PyObject *self,iMS::Image const &img,iMS::ImageRepeats const &Rpt=iMS::ImageRepeats::NONE,int const rpts=0);
    SwigDirector_ImageSequenceEntry(PyObject *self,iMS::ImageTableEntry const &ite,iMS::kHz const &InternalClock,iMS::ImageRepeats const &Rpt=iMS::ImageRepeats::NONE,int const rpts=0);
    SwigDirector_ImageSequenceEntry(PyObject *self,iMS::ImageTableEntry const &ite,int const ExtClockDivide,iMS::ImageRepeats const &Rpt=iMS::ImageRepeats::NONE,int const rpts=0);
    SwigDirector_ImageSequenceEntry(PyObject *self,iMS::ImageSequenceEntry const &arg0);
    SwigDirector_ImageSequenceEntry(PyObject *self,iMS::SequenceEntry const &arg0);
    virtual ~SwigDirector_ImageSequenceEntry();
    virtual bool operator ==(iMS::SequenceEntry const &rhs) const;

/* Internal director utilities */
public:
    bool swig_get_inner(const char *swig_protected_method_name) const {
      std::map<std::string, bool>::const_iterator iv = swig_inner.find(swig_protected_method_name);
      return (iv != swig_inner.end() ? iv->second : false);
    }
    void swig_set_inner(const char *swig_protected_method_name, bool swig_val) const {
      swig_inner[swig_protected_method_name] = swig_val;
    }
private:
    mutable std::map<std::string, bool> swig_inner;

#if defined(SWIG_PYTHON_DIRECTOR_VTABLE)
/* VTable implementation */
    PyObject *swig_get_method(size_t method_index, const char *method_name) const {
      PyObject *method = vtable[method_index];
      if (!method) {
        swig::SwigVar_PyObject name = SWIG_Python_str_FromChar(method_name);
        method = PyObject_GetAttr(swig_get_self(), name);
        if (!method) {
          std::string msg = "Method in class ImageSequenceEntry doesn't exist, undefined ";
          msg += method_name;
          Swig::DirectorMethodException::raise(msg.c_str());
        }
        vtable[method_index] = method;
      }
      return method;
    }
private:
    mutable swig::SwigVar_PyObject vtable[1];
#endif

};


struct SwigDirector_ToneSequenceEntry : public iMS::ToneSequenceEntry, public Swig::Director {

public:
    SwigDirector_ToneSequenceEntry(PyObject *self);
    SwigDirector_ToneSequenceEntry(PyObject *self,iMS::ToneBuffer const &tb,iMS::SignalPath::ToneBufferControl tbc=iMS::SignalPath::ToneBufferControl::HOST,unsigned int const initial_index=0);
    SwigDirector_ToneSequenceEntry(PyObject *self,iMS::ToneSequenceEntry const &arg0);
    SwigDirector_ToneSequenceEntry(PyObject *self,iMS::SequenceEntry const &entry);
    virtual ~SwigDirector_ToneSequenceEntry();
    virtual bool operator ==(iMS::SequenceEntry const &rhs) const;

/* Internal director utilities */
public:
    bool swig_get_inner(const char *swig_protected_method_name) const {
      std::map<std::string, bool>::const_iterator iv = swig_inner.find(swig_protected_method_name);
      return (iv != swig_inner.end() ? iv->second : false);
    }
    void swig_set_inner(const char *swig_protected_method_name, bool swig_val) const {
      swig_inner[swig_protected_method_name] = swig_val;
    }
private:
    mutable std::map<std::string, bool> swig_inner;

#if defined(SWIG_PYTHON_DIRECTOR_VTABLE)
/* VTable implementation */
    PyObject *swig_get_method(size_t method_index, const char *method_name) const {
      PyObject *method = vtable[method_index];
      if (!method) {
        swig::SwigVar_PyObject name = SWIG_Python_str_FromChar(method_name);
        method = PyObject_GetAttr(swig_get_self(), name);
        if (!method) {
          std::string msg = "Method in class ToneSequenceEntry doesn't exist, undefined ";
          msg += method_name;
          Swig::DirectorMethodException::raise(msg.c_str());
        }
        vtable[method_index] = method;
      }
      return method;
    }
private:
    mutable swig::SwigVar_PyObject vtable[1];
#endif

};


#endif
